{"flag_1"
	{on spawn
		{call "add_number"}
		{delay 1
			{view start "fx"}
		}
	}
	{on "add_number" overload
		{add_view "flag_1" "fx" "fx_number" not_scenario}
	}
}

{"flag_2"
	{on spawn
		{call "add_number"}
		{delay 1
			{view start "fx"}
		}
	}
	{on "add_number" overload
		{add_view "flag_2" "fx" "fx_number" not_scenario}
	}
}

{"flag_3"
	{on spawn
		{call "add_number"}
		{delay 1
			{view start "fx"}
		}
	}
	{on "add_number" overload
		{add_view "flag_3" "fx" "fx_number" not_scenario}
	}
}

{"flag_4"
	{on spawn
		{call "add_number"}
		{delay 1
			{view start "fx"}
		}
	}
	{on "add_number" overload
		{add_view "flag_4" "fx" "fx_number" not_scenario}
	}
}

{"flag_5"
	{on spawn
		{call "add_number"}
		{delay 1
			{view start "fx"}
		}
	}
	{on "add_number" overload
		{add_view "flag_5" "fx" "fx_number" not_scenario}
	}
}

{"flag_6"
	{on spawn
		{call "add_number"}
		{delay 1
			{view start "fx"}
		}
	}
	{on "add_number" overload
		{add_view "flag_6" "fx" "fx_number" not_scenario}
	}
}

{"flag_7"
	{on spawn
		{call "add_number"}
		{delay 1
			{view start "fx"}
		}
	}
	{on "add_number" overload
		{add_view "flag_7" "fx" "fx_number" not_scenario}
	}
}

{"flag_8"
	{on spawn
		{call "add_number"}
		{delay 1
			{view start "fx"}
		}
	}
	{on "add_number" overload
		{add_view "flag_8" "fx" "fx_number" not_scenario}
	}
}

{"flag_9"
	{on spawn
		{call "add_number"}
		{delay 1
			{view start "fx"}
		}
	}
	{on "add_number" overload
		{add_view "flag_9" "fx" "fx_number" not_scenario}
	}
}

{"flag_10"
	{on spawn
		{call "add_number"}
		{delay 1
			{view start "fx"}
		}
	}
	{on "add_number" overload
		{add_view "flag_10"	"fx" "fx_number" not_scenario}
	}
}

{"flag_11"
	{on spawn
		{call "add_number"}
		{delay 1
			{view start "fx"}
		}
	}
	{on "add_number" overload
		{add_view "flag_11"	"fx" "fx_number" not_scenario}
	}
}

{"flag_12"
	{on spawn
		{call "add_number"}
		{delay 1
			{view start "fx"}
		}
	}
	{on "add_number" overload
		{add_view "flag_12"	"fx" "fx_number" not_scenario}
	}
}

{"flag_13"
	{on spawn
		{call "add_number"}
		{delay 1
			{view start "fx"}
		}
	}
	{on "add_number" overload
		{add_view "flag_13"	"fx" "fx_number" not_scenario}
	}
}

{"flag_14"
	{on spawn
		{call "add_number"}
		{delay 1
			{view start "fx"}
		}
	}
	{on "add_number" overload
		{add_view "flag_14"	"fx" "fx_number" not_scenario}
	}
}

{"flag_15"
	{on spawn
		{call "add_number"}
		{delay 1
			{view start "fx"}
		}
	}
	{on "add_number" overload
		{add_view "flag_15"	"fx" "fx_number" not_scenario}
	}
}

{"flag_16"
	{on spawn
		{call "add_number"}
		{delay 1
			{view start "fx"}
		}
	}
	{on "add_number" overload
		{add_view "flag_16"	"fx" "fx_number" not_scenario}
	}
}

{"flag_17"
	{on spawn
		{call "add_number"}
		{delay 1
			{view start "fx"}
		}
	}
	{on "add_number" overload
		{add_view "flag_17"	"fx" "fx_number" not_scenario}
	}
}

{"flag_ammo"
	{on spawn
		{call "add_number"}
		{delay 1
			{view start "fx"}
		}
	}
	{on "add_number" overload
		{add_view "flag_ammo"	"fx" "fx_number" not_scenario}
	}
}

{"supply_ammo"
	{on spawn
		{call "add_number"}
		{delay 1
			{view start "fx"}
		}
	}
	{on "add_number" overload
		{add_view "supply_ammo"	"fx" "fx_number" not_scenario}
	}
}

{"evacuation"
	{on spawn
		{call "add_number"}
		{delay 1
			{view start "fx"}
		}
	}
	{on "add_number" overload
		{add_view "evacuation"	"fx" "ammo" not_scenario}
	}
}

{"fortification"
	{on spawn
		{call "add_number"}
		{delay 1
			{view start "fx"}
		}
	}
	{on "add_number" overload
		{add_view "fortification"	"fx" "fx_number" not_scenario}
	}
}

{"spawn"
	{on spawn
		{call "add_number"}
		{delay 1
			{view start "fx"}
		}
	}
	{on "add_number" overload
		{add_view "spawn"	"fx" "fx_number" not_scenario}
	}
}

{"mp_watchout"
	{on spawn
		{call "add_number"}
		{delay 0
			{view start "fx"}
		}
	}
	{on "add_number" overload
		{add_view "mp_watchout" "fx" "fx_mp_pointer" not_scenario}
	}
}

{"mp_attack"
	{on spawn
		{call "add_number"}
		{delay 0
			{view start "fx"}
		}
	}
	{on "add_number" overload
		{add_view "mp_attack" "fx" "fx_mp_pointer" not_scenario}
	}
}

{"mp_defend"
	{on spawn
		{call "add_number"}
		{delay 0
			{view start "fx"}
		}
	}
	{on "add_number" overload
		{add_view "mp_defend" "fx" "fx_mp_pointer" not_scenario}
	}
}

{"mp_enemy"
	{on spawn
		{call "add_number"}
		{delay 0
			{view start "fx"}
		}
	}
	{on "add_number" overload
		{add_view "mp_enemy" "fx" "fx_mp_pointer" not_scenario}
	}
}

{"mp_going"
	{on spawn
		{call "add_number"}
		{delay 0
			{view start "fx"}
		}
	}
	{on "add_number" overload
		{add_view "mp_going" "fx" "fx_mp_pointer" not_scenario}
	}
}

{"mp_help"
	{on spawn
		{call "add_number"}
		{delay 0
			{view start "fx"}
		}
	}
	{on "add_number" overload
		{add_view "mp_help" "fx" "fx_mp_pointer" not_scenario}
	}
}

{"grenade smoke paradrop_ammo"
	{on "add_smoke" overload
		{add_view "smoke_yellow_small" "smoke1" "root"}
		{add_view "smoke_yellow_norm" "smoke2" "root"}
		{add_view "smoke_yellow_norm" "smoke3" "root"}
	}
	{on "activate"
		{delay 10.0
			{hide 1}
			{spawn "paradrop_ammo"}
			{start_sound "world/ambient/bomber_flyby.wav"}
		}
	}
}
{"grenade smoke paradrop_ammo_heavy"
	{on "add_smoke" overload
		{add_view "smoke_yellow_small" "smoke1" "root"}
		{add_view "smoke_yellow_norm" "smoke2" "root"}
		{add_view "smoke_yellow_norm" "smoke3" "root"}
	}
	{on "activate"
		{delay 10.0
			{hide 1}
			{spawn "paradrop_ammo_heavy"}
			{start_sound "world/ambient/bomber_flyby.wav"}
		}
	}
}
{"paradrop"
	{on spawn
		{ani_play "flight"}
		{delay 4.0
			{ani_play "landing"}
		}
	}
}