{"flag_1"
    {on spawn
        {call "add_number"}
        {delay 1
            {view start "fx"}
        }
    }
	{on "add_number" overload
		{add_view "flag_1" "fx" "fx_number"}
		{add_view "skirmish_flag_border" "fx" "fx_number"}
	}
}

{"flag_2"
    {on spawn
        {call "add_number"}
        {delay 1
            {view start "fx"}
        }
    }
	{on "add_number" overload
		{add_view "flag_2" "fx" "fx_number"}
		{add_view "skirmish_flag_border" "fx" "fx_number"}
	}
}

{"flag_3"
    {on spawn
        {call "add_number"}
        {delay 1
            {view start "fx"}
        }
    }
	{on "add_number" overload
		{add_view "flag_3" "fx" "fx_number"}
		{add_view "skirmish_flag_border" "fx" "fx_number"}
	}
}

{"flag_4"
    {on spawn
        {call "add_number"}
        {delay 1
            {view start "fx"}
        }
    }
	{on "add_number" overload
		{add_view "flag_4" "fx" "fx_number"}
		{add_view "skirmish_flag_border" "fx" "fx_number"}
	}
}

{"flag_5"
    {on spawn
        {call "add_number"}
        {delay 1
            {view start "fx"}
        }
    }
	{on "add_number" overload
		{add_view "flag_5" "fx" "fx_number"}
		{add_view "skirmish_flag_border" "fx" "fx_number"}
	}
}

{"flag_6"
    {on spawn
        {call "add_number"}
        {delay 1
            {view start "fx"}
        }
    }
	{on "add_number" overload
		{add_view "flag_6" "fx" "fx_number"}
		{add_view "skirmish_flag_border" "fx" "fx_number"}
	}
}

{"flag_7"
    {on spawn
        {call "add_number"}
        {delay 1
            {view start "fx"}
        }
    }
	{on "add_number" overload
		{add_view "flag_7" "fx" "fx_number"}
		{add_view "skirmish_flag_border" "fx" "fx_number"}
	}
}

{"flag_8"
    {on spawn
        {call "add_number"}
        {delay 1
            {view start "fx"}
        }
    }
	{on "add_number" overload
		{add_view "flag_8" "fx" "fx_number"}
		{add_view "skirmish_flag_border" "fx" "fx_number"}
	}
}

{"flag_9"
    {on spawn
        {call "add_number"}
        {delay 1
            {view start "fx"}
        }
    }
	{on "add_number" overload
		{add_view "flag_9" "fx" "fx_number"}
		{add_view "skirmish_flag_border" "fx" "fx_number"}
	}
}

{"flag_10"
    {on spawn
        {call "add_number"}
        {delay 1
            {view start "fx"}
        }
    }
	{on "add_number" overload
		{add_view "flag_10"	"fx" "fx_number"}
		{add_view "skirmish_flag_border" "fx" "fx_number"}
	}
}

{"flag_11"
    {on spawn
        {call "add_number"}
        {delay 1
            {view start "fx"}
        }
    }
	{on "add_number" overload
		{add_view "flag_11"	"fx" "fx_number"}
		{add_view "skirmish_flag_border" "fx" "fx_number"}
	}
}

{"flag_12"
    {on spawn
        {call "add_number"}
        {delay 1
            {view start "fx"}
        }
    }
	{on "add_number" overload
		{add_view "flag_12"	"fx" "fx_number"}
		{add_view "skirmish_flag_border" "fx" "fx_number"}
	}
}

{"flag_13"
    {on spawn
        {call "add_number"}
        {delay 1
            {view start "fx"}
        }
    }
	{on "add_number" overload
		{add_view "flag_13"	"fx" "fx_number"}
		{add_view "skirmish_flag_border" "fx" "fx_number"}
	}
}

{"flag_14"
    {on spawn
        {call "add_number"}
        {delay 1
            {view start "fx"}
        }
    }
	{on "add_number" overload
		{add_view "flag_14"	"fx" "fx_number"}
		{add_view "skirmish_flag_border" "fx" "fx_number"}
	}
}

{"flag_15"
    {on spawn
        {call "add_number"}
        {delay 1
            {view start "fx"}
        }
    }
	{on "add_number" overload
		{add_view "flag_15"	"fx" "fx_number"}
		{add_view "skirmish_flag_border" "fx" "fx_number"}
	}
}

{"flag_16"
    {on spawn
        {call "add_number"}
        {delay 1
            {view start "fx"}
        }
    }
	{on "add_number" overload
		{add_view "flag_16"	"fx" "fx_number"}
		{add_view "skirmish_flag_border" "fx" "fx_number"}
	}
}

{"flag_17"
    {on spawn
        {call "add_number"}
        {delay 1
            {view start "fx"}
        }
    }
	{on "add_number" overload
		{add_view "flag_17"	"fx" "fx_number"}
		{add_view "skirmish_flag_border" "fx" "fx_number"}
	}
}

{"flag_frontlines"
    {on spawn
        {call "add_number"}
        {delay 1
            {view start "fx"}
        }
    }
	{on "add_number" overload
		{add_view "flag_frontlines"	"fx" "fx_number"}
		{add_view "skirmish_flag_border" "fx" "fx_number"}
	}
}

{"flag_frontlines_slave"
    {on spawn
        {call "add_number"}
        {delay 1
            {view start "fx"}
        }
    }
	{on "add_number" overload
		{add_view "flag_frontlines_slave" "fx" "fx_number"}
		{add_view "skirmish_flag_border" "fx" "fx_number"}
	}
}

{"spawn"
    {on spawn
        {call "add_number"}
        {delay 1
            {view start "fx"}
        }
    }
	{on "add_number" overload
		{add_view "spawn"	"fx" "fx_number"}
		{add_view "skirmish_flag_border" "fx" "fx_number"}
	}
}

{"mp_pointer"
    {on spawn
        {call "add_number"}
		{delay 0
            {view start "fx"}
		}
    }
	{on "add_number" overload
		{add_view "mp_pointer" "fx" "fx_mp_pointer"}
		{add_view "skirmish_flag_border" "fx" "fx_number"}
	}
}


{"grenade smoke paradrop_ammo"
	{on "add_smoke" overload
		{add_view "smoke_yellow_small" "smoke1" "root"}
		{add_view "smoke_yellow_norm" "smoke2" "root"}
		{add_view "smoke_yellow_norm" "smoke3" "root"}
	}
	{on "activate"
		{delay 10.0
			{hide 1}
            {spawn "paradrop_ammo"}
			{start_sound "world/ambient/bomber_flyby.wav"}
		}
	}
}
{"grenade smoke paradrop_ammo_heavy"
	{on "add_smoke" overload
		{add_view "smoke_yellow_small" "smoke1" "root"}
		{add_view "smoke_yellow_norm" "smoke2" "root"}
		{add_view "smoke_yellow_norm" "smoke3" "root"}
	}
	{on "activate"
		{delay 10.0
			{hide 1}
            {spawn "paradrop_ammo_heavy"}
			{start_sound "world/ambient/bomber_flyby.wav"}
		}
	}
}
{"paradrop"
	{on spawn
		{ani_play "flight"}
		{delay 4.0
			{ani_play "landing"}
		}
	}
}