{easy
	{balancingFactorBonus {cp 0.40} {mpStart 2.5}  {mpFinish 2.5} {mp 30.00} {payback 2.00} {charge 1} }
	{chargeFactors
		{value "*=1.0"}
	}
}
{normal
	{balancingFactorBonus {cp 0.50} {mpStart 4.5}  {mpFinish 4.5} {mp 30.00} {payback 4.00} {charge 1} }
	{chargeFactors
		{value "*=1.0"}
	}
}
{hard
	{balancingFactorBonus {cp 0.70} {mpStart 9.0}  {mpFinish 9.0} {mp 30.00} {payback 8.00} {charge 1} }
	{chargeFactors
		{value "*=1.0"}
	}
}
{heroic
	{balancingFactorBonus {cp 0.80} {mpStart 18.0}  {mpFinish 18.0} {mp 30.00} {payback 16.00} {charge 1} }
	{chargeFactors
		{value "*=1.0"}
	}
}