{easy
	{balancingFactorBonus {cp 0.25} {mpStart 1.0}  {mpFinish 1.0} {mp 30.00} {payback 1.00} {charge 1} }
	{chargeFactors
		{value "*=1.0"}
	}
}
{normal
	{balancingFactorBonus {cp 0.30} {mpStart 2.0}  {mpFinish 2.0} {mp 30.00} {payback 2.00} {charge 2} }
	{chargeFactors
		{value "*=2.0"}
	}
}
{hard
	{balancingFactorBonus {cp 0.40} {mpStart 4.0}  {mpFinish 4.0} {mp 30.00} {payback 4.00} {charge 4} }
	{chargeFactors
		{value "*=4.0"}
	}
}
{heroic
	{balancingFactorBonus {cp 0.50} {mpStart 8.0}  {mpFinish 8.0} {mp 30.00} {payback 8.00} {charge 8} }
	{chargeFactors
		{value "*=8.0"}
	}
}