{easy
	{balancingFactorBonus {cp 0.25} {mpStart 1.5}  {mpFinish 1.5} {mp 30.00} {payback 1.00} {charge 1} }
	{chargeFactors
		{value "*=1.0"}
	}
}
{normal
	{balancingFactorBonus {cp 0.30} {mpStart 3.0}  {mpFinish 3.0} {mp 30.00} {payback 2.00} {charge 1} }
	{chargeFactors
		{value "*=1.0"}
	}
}
{hard
	{balancingFactorBonus {cp 0.40} {mpStart 6.0}  {mpFinish 6.0} {mp 30.00} {payback 4.00} {charge 1} }
	{chargeFactors
		{value "*=1.0"}
	}
}
{heroic
	{balancingFactorBonus {cp 0.50} {mpStart 9.0}  {mpFinish 9.0} {mp 30.00} {payback 8.00} {charge 1} }
	{chargeFactors
		{value "*=1.0"}
	}
}