(define "perk_assault"
	{"health"				"200%"}
	{"health_regeneration"	"200%"}
	{"stamina"				"150%"}
	{"stamina_regeneration"	"100%"}

	{"vision" "human"}
	{"speed" 1.0}

	{"pistol"			lvl_1}
	{"smg"				lvl_2}
	{"mgun"				lvl_1}
	{"rifle"			lvl_5}
	{"rocketlauncher"	lvl_1}
	{"melee"			lvl_1}
)
(define "perk_mg"
	{"health"				"300%"}
	{"health_regeneration"	"100%"}
	{"stamina"				"100%"}
	{"stamina_regeneration"	"150%"}

	{"vision" "human"}
	{"speed" 0.8}

	{"pistol"			lvl_3}
	{"smg"				lvl_1}
	{"mgun"				lvl_3}
	{"rifle"			lvl_1}
	{"rocketlauncher"	lvl_1}
	{"melee"			lvl_1}
)
(define "perk_scout"
	{"health"				"200%"}
	{"health_regeneration"	"100%"}
	{"stamina"				"200%"}
	{"stamina_regeneration"	"150%"}

	{"vision" "human"}
	{"speed" 1.2}

	{"pistol"			lvl_1}
	{"smg"				lvl_5}
	{"mgun"				lvl_1}
	{"rifle"			lvl_1}
	{"rocketlauncher"	lvl_1}
	{"melee"			lvl_3}
)
(define "perk_marksman"
	{"health"				"200%"}
	{"health_regeneration"	"100%"}
	{"stamina"				"150%"}
	{"stamina_regeneration"	"100%"}

	{"vision" "human"}
	{"speed" 1.0}

	{"pistol"			lvl_1}
	{"smg"				lvl_1}
	{"mgun"				lvl_1}
	{"rifle"			lvl_5}
	{"rocketlauncher"	lvl_1}
	{"melee"			lvl_1}
	
	{"aimedshot"}
)
(define "perk_shotgunner"
	{"health"				"200%"}
	{"health_regeneration"	"200%"}
	{"stamina"				"200%"}
	{"stamina_regeneration"	"150%"}

	{"vision" "human"}
	{"speed" 1.1}

	{"pistol"			lvl_4}
	{"smg"				lvl_1}
	{"mgun"				lvl_1}
	{"rifle"			lvl_3}
	{"rocketlauncher"	lvl_1}
	{"melee"			lvl_3}
)
(define "perk_specop"
	{"health"				"250%"}
	{"health_regeneration"	"300%"}
	{"stamina"				"100%"}
	{"stamina_regeneration"	"200%"}

	{"vision" "human"}
	{"speed" 1.1}

	{"pistol"			lvl_3}
	{"smg"				lvl_5}
	{"mgun"				lvl_3}
	{"rifle"			lvl_3}
	{"rocketlauncher"	lvl_1}
	{"melee"			lvl_5}
)
(define "perk_heavy_assault"
	{"health"				"250%"}
	{"health_regeneration"	"200%"}
	{"stamina"				"200%"}
	{"stamina_regeneration"	"150%"}

	{"vision" "human"}
	{"speed" 1.0}

	{"pistol"			lvl_2}
	{"smg"				lvl_4}
	{"mgun"				lvl_2}
	{"rifle"			lvl_2}
	{"rocketlauncher"	lvl_5}
	{"melee"			lvl_2}
)
(define "perk_sniper"
	{"health"				"100%"}
	{"health_regeneration"	"100%"}
	{"stamina"				"100%"}
	{"stamina_regeneration"	"100%"}

	{"vision" "human"}
	{"speed" 1.0}

	{"pistol"			lvl_3}
	{"smg"				lvl_1}
	{"mgun"				lvl_1}
	{"rifle"			lvl_5}
	{"rocketlauncher"	lvl_1}
	{"melee"			lvl_1}
	
	{"aimedshot"}
)