{Extender "light"
	{preset "lamp_spot"
		{light_fx 	"light_post_dir"}
		{light_bone "lamp_light_spot1"}
		{break_fx 	"lamp_hit"}
		{break_bone "lamp_glass1"}
	}
	{preset "lamp_spot_yellow"
		{light_fx 	"light_post_dir_yellow"}
		{light_bone "lamp_light_spot1"}
		{break_fx 	"lamp_hit"}
		{break_bone "lamp_glass1"}
	}
	{preset "lamp_point"
		{light_fx 	"light_post_plafond"}
		{light_bone "lamp_light_point1"}
		{break_fx 	"lamp_hit"}
		{break_bone "lamp_glass1"}
	}
}