{Skeleton
{TexMods
	{"Autumn"		"aut"		}
   	{"Autumn1"		"aut1"		}
   	{"Autumn2"		"aut2"		}
   	{"Autumn3"		"aut3"		}
	{"AutumnL"		"autlate"	}
	{"AutumnL1"		"autlate1"	}
	{"AutumnL2"		"autlate2"	}
	{"AutumnL3"		"autlate3"	}
	{"Bare"			"bare"		}
	{"Bare1"		"bare1"		}
	{"Bare2"		"bare2"		}
	{"Light"		"light_win2"}
	{"November1"	"nov1"		}
	{"November"		"nov"		}
	{"Barewinter"	"barewin"	}
	{"Winter"		"win"		}
	{"Winter1"		"win1"		}
	{"Winter2"		"win2"		}
	{"Broken"		"broken"	}
	{"V1"			"1"			}
	{"V1_Autumn"	"1aut"		}
	{"V1_Autumn1"	"1aut1"		}
	{"V1_Autumnl"	"1autlate"	}
	{"V1_Bare"		"1bare"		}
	{"V1_Bare1"		"1bare1"	}
	{"V1_Winter"	"1win"		}
	{"V1_Winter1"	"1win1"		}
	{"V1_Winter2"	"1win2"		}
	{"V1_Spring"	"1spring"	}
	{"V2"			"2"			}
	{"V2_Autumn"	"2aut"		}
	{"V2_Autumnl"	"2autlate"		}
	{"V3"			"3"			}
	{"V4"			"4"			}
	{"V5"			"5"			}
	{"V6"			"6"			}
	{"V7"			"7"			}
	{"V8"			"8"			}
	{"V9"			"9"			}
	{"V10"			"10"			}
	{"Spring"		"spring"	}
	{"Spring1"		"spring1"	}
}
;texmods for morphing when burning
{TexMods
	{"_burned0"		"autlate"	}
	{"_burned1"		"bare"		}
;	{"_burned2"		"broken"	}
	{"_burned3"		"burned"	}
	{"_crushed"		"crushed"	}
}
;texmods for morphing when winter tree fall
{TexMods
	{"_win0"		"win3"		}
}
}
