{Skeleton
	{TexMods
		{"_x"       "_x"      }
		{"1"        "1"       }
		{"1_x"      "1_x"     }
		{"2"        "2"       }
		{"2_x"      "2_x"     }
		{"3"        "3"       }
		{"3_x"      "3_x"     }
		{"4"        "4"       }
		{"4_x"      "4_x"     }
		{"5"        "5"       }
		{"5_x"      "5_x"     }
		{"6"        "6"       }
		{"6_x"      "6_x"     }
		{"7"        "7"       }
		{"7_x"      "7_x"     }
		{"8"        "8"       }
		{"8_x"      "8_x"     }
		{"9"        "9"       }
		{"9_x"      "9_x"     }
		{"10"       "10"      }
		{"10_x"     "10_x"    }
		{"11"       "11"      }
		{"11_x"     "11_x"    }
		{"22"       "22"      }
    	{"November"	"nov"	  }
    	{"Winter"	"win"	  }
	    {"Winter1"	"win1"	  }
	    {"Winter2"	"win2"	  }
		{"Dutch"    "dutch"	  }
		{"Dutch_x"  "dutch_x" }
		{"Dutch1"   "dutch1"  }
		{"Dutch1_x" "dutch1_x"}
		{"Dutch2"   "dutch2"  }
		{"Dutch2_x" "dutch2_x"}
		{"Dutch3"   "dutch3"  }
		{"Dutch3_x" "dutch3_x"}
		{"Dutch4"   "dutch4"  }
		{"Dutch4_x" "dutch4_x"}
		{"Dutch5"   "dutch5"  }
		{"Dutch5_x" "dutch5_x"}
		{"poster1"  "poster1" }
		{"poster2"  "poster2" }
		{"poster3"  "poster3" }
		{"poster4"  "poster4" }
		{"poster5"  "poster5" }
	}
}
