(define "level_standard" 
	{level "10%"	0.1		}
	{level "25%"	0.25	}
	{level "50%"	0.5		}
	{level "75%"	0.75	}
	{level "100%"	1.0		}
	{level "125%"	1.25	}
	{level "150%"	1.5		}
	{level "175%"	1.75	}
	{level "200%"	2.0		}
	{level "225%"	2.25	}
	{level "250%"	2.5		}
	{level "275%"	2.75	}
	{level "300%"	3.0		}
	{level "325%"	3.25	}
	{level "350%"	3.5		}
	{level "375%"	3.75	}
	{level "400%"	4.0		}
	{level "425%"	4.25	}
	{level "450%"	4.5		}
	{level "475%"	4.75	}
	{level "500%"	5.0		}
	{level "600%"	6.0		}
	{level "750%"	7.5		}
	{level "1000%"	10.0	}
)