(define "perk_home_guard"
		{"health" "100%"
		}
		{"health_regeneration" "100%"
		}
		{"stamina" "100%"
		}
		{"stamina_regeneration" "100%"
		}
		{"resources" "100%"
		}		
		{"vision" "mp_soldier"
		}
		{"speed" 0.7
		}
		{"tank"	0.3
		}
		
		{"pistol" lvl_1
		}
		{"smg" lvl_1
		}
		{"mgun" lvl_2
		}
		{"rifle" lvl_1
		}
		{"rocketlauncher" lvl_1
		}
		{"melee" lvl_2
		}
		
		(include "perks_generic.inc")
		{fortification}
;		{mechanic}
		("barricade_engineer")		
)
(define "perk_smg"
		{"health" "150%"
		}
		{"health_regeneration" "100%"
		}
		{"stamina" "100%"
		}
		{"stamina_regeneration" "100%"
		}
		{"resources" "100%"
		}		
		{"vision" "mp_soldier"
		}
		{"speed" 0.9
		}
		{"tank"	0.3
		}
		
		{"pistol" lvl_2
		}
		{"smg" lvl_2
		}
		{"mgun" lvl_1
		}
		{"rifle" lvl_1
		}
		{"rocketlauncher" lvl_1
		}
		{"melee" lvl_2
		}
		
		{"personage" 1
		}		
		
		(include "perks_generic.inc")
		{fortification}
;		{mechanic}
		("barricade_engineer")		
)
(define "perk_rifle"
		{"health" "150%"
		}
		{"health_regeneration" "100%"
		}
		{"stamina" "100%"
		}
		{"stamina_regeneration" "100%"
		}
		{"resources" "100%"
		}		
		{"vision" "mp_soldier"
		}
		{"speed" 0.9
		}
		{"tank"	0.3
		}
		
		{"pistol" lvl_1
		}
		{"smg" lvl_1
		}
		{"mgun" lvl_1
		}
		{"rifle" lvl_2
		}
		{"rocketlauncher" lvl_1
		}
		{"melee" lvl_2
		}
		
		{"personage" 1
		}		
		
		(include "perks_generic.inc")
		{fortification}
;		{mechanic}
		("barricade_engineer")		
)
(define "perk_miner"
		{"health" "200%"
		}
		{"health_regeneration" "100%"
		}
		{"stamina" "100%"
		}
		{"stamina_regeneration" "100%"
		}
		{"resources" "100%"
		}		
		{"vision" "mp_soldier"
		}
		{"speed" 0.9
		}
		{"tank"	0.3
		}
		
		{"pistol" lvl_3
		}
		{"smg" lvl_2
		}
		{"mgun" lvl_1
		}
		{"rifle" lvl_2
		}
		{"rocketlauncher" lvl_1
		}
		{"melee" lvl_2
		}
		
		{"personage" 1
		}		
		
		(include "perks_generic.inc")
		{fortification}
;		{mechanic}
		("barricade_engineer")		
)
(define "perk_at_rifle"
		{"health" "150%"
		}
		{"health_regeneration" "100%"
		}
		{"stamina" "100%"
		}
		{"stamina_regeneration" "100%"
		}
		{"resources" "100%"
		}		
		{"vision" "mp_soldier"
		}
		{"speed" 0.9
		}
		{"tank"	0.3
		}
		
		{"pistol" lvl_2
		}
		{"smg" lvl_2
		}
		{"mgun" lvl_1
		}
		{"rifle" lvl_3
		}
		{"rocketlauncher" lvl_1
		}
		{"melee" lvl_2
		}
		
		{"personage" 1
		}		
		
		(include "perks_generic.inc")
		{fortification}
;		{mechanic}
		("barricade_engineer")		
)
(define "perk_bazooker"
		{"health" "150%"
		}
		{"health_regeneration" "100%"
		}
		{"stamina" "100%"
		}
		{"stamina_regeneration" "100%"
		}
		{"resources" "100%"
		}		
		{"vision" "mp_soldier"
		}
		{"speed" 0.9
		}
		{"tank"	0.3
		}
		
		{"pistol" lvl_2
		}
		{"smg" lvl_2
		}
		{"mgun" lvl_1
		}
		{"rifle" lvl_1
		}
		{"rocketlauncher" lvl_3
		}
		{"melee" lvl_2
		}
		
		{"personage" 1
		}		
		
		(include "perks_generic.inc")
		{fortification}
;		{mechanic}
		("barricade_engineer")		
)
(define "perk_elite"
		{"health" "250%"
		}
		{"health_regeneration" "150%"
		}
		{"stamina" "150%"
		}
		{"stamina_regeneration" "150%"
		}
		{"resources" "100%"
		}		
		{"vision" "mp_soldier"
		}
		{"speed" 1.2
		}
		{"tank"	1.0
		}
		
		{"pistol" lvl_3
		}
		{"smg" lvl_3
		}
		{"mgun" lvl_3
		}
		{"rifle" lvl_3
		}
		{"rocketlauncher" lvl_3
		}
		{"melee" lvl_3
		}
		
		{"personage" 1
		}		
		
		(include "perks_generic.inc")
		{fortification}
;		{mechanic}
		("barricade_engineer")		
)
(define "perk_flamer"
		{"health" "250%"
		}
		{"health_regeneration" "100%"
		}
		{"stamina" "100%"
		}
		{"stamina_regeneration" "100%"
		}
		{"resources" "100%"
		}		
		{"vision" "mp_soldier"
		}
		{"speed" 0.9
		}
		{"tank"	0.3
		}
		
		{"pistol" lvl_2
		}
		{"smg" lvl_2
		}
		{"mgun" lvl_1
		}
		{"rifle" lvl_1
		}
		{"rocketlauncher" lvl_1
		}
		{"melee" lvl_2
		}
		
		{"personage" 1
		}		
		
		(include "perks_generic.inc")
		{fortification}
;		{mechanic}
		("barricade_engineer")		
)
(define "perk_medic"
		{"health" "250%"
		}
		{"health_regeneration" "100%"
		}
		{"stamina" "200%"
		}
		{"stamina_regeneration" "100%"
		}
		{"resources" "100%"
		}		
		{"vision" "mp_soldier"
		}
		{"speed" 1.4
		}
		{"tank"	0.3
		}
		
		{"pistol" lvl_1
		}
		{"smg" lvl_1
		}
		{"mgun" lvl_1
		}
		{"rifle" lvl_1
		}
		{"rocketlauncher" lvl_1
		}
		{"melee" lvl_1
		}
		
		{"personage" 1
		}
		{"medic" 10.0
		}		
		
		(include "perks_generic.inc")
		{fortification}
;		{mechanic}
		("barricade_engineer")		
)
(define "perk_mgun"
		{"health" "150%"
		}
		{"health_regeneration" "100%"
		}
		{"stamina" "200%"
		}
		{"stamina_regeneration" "150%"
		}
		{"resources" "100%"
		}		
		{"vision" "mp_soldier"
		}
		{"speed" 1.2
		}
		{"tank"	0.3
		}
		
		{"pistol" lvl_1
		}
		{"smg" lvl_1
		}
		{"mgun" lvl_2
		}
		{"rifle" lvl_1
		}
		{"rocketlauncher" lvl_1
		}
		{"melee" lvl_2
		}
		
		{"personage" 1
		}		
		
		(include "perks_generic.inc")
		{fortification}
;		{mechanic}
		("barricade_engineer")		
)
(define "perk_oficer"
		{"health" "200%"
		}
		{"health_regeneration" "100%"
		}
		{"stamina" "200%"
		}
		{"stamina_regeneration" "150%"
		}
		{"resources" "100%"
		}		
		{"vision" "mp_soldier"
		}
		{"speed" 1.0
		}
		{"tank"	0.9
		}
		
		{"pistol" lvl_3
		}
		{"smg" lvl_3
		}
		{"mgun" lvl_3
		}
		{"rifle" lvl_3
		}
		{"rocketlauncher" lvl_3
		}
		{"melee" lvl_3
		}
		
		{"personage" 1
		}		
		
		(include "perks_generic.inc")
		{fortification}
;		{mechanic}
		("barricade_engineer")		
)
(define "perk_rfdioman"
		{"health" "100%"
		}
		{"health_regeneration" "100%"
		}
		{"stamina" "100%"
		}
		{"stamina_regeneration" "100%"
		}
		{"resources" "100%"
		}		
		{"vision" "mp_soldier"
		}
		{"speed" 0.9
		}
		{"tank"	0.3
		}
		
		{"pistol" lvl_1
		}
		{"smg" lvl_1
		}
		{"mgun" lvl_1
		}
		{"rifle" lvl_1
		}
		{"rocketlauncher" lvl_1
		}
		{"melee" lvl_1
		}
		
		{"personage" 1
		}		
		
		(include "perks_generic.inc")
		{fortification}
;		{mechanic}
		("barricade_engineer")		
)
(define "perk_saper"
		{"health" "100%"
		}
		{"health_regeneration" "100%"
		}
		{"stamina" "100%"
		}
		{"stamina_regeneration" "100%"
		}
		{"resources" "100%"
		}		
		{"vision" "mp_soldier"
		}
		{"speed" 0.9
		}
		{"tank"	0.3
		}
		
		{"pistol" lvl_1
		}
		{"smg" lvl_1
		}
		{"mgun" lvl_1
		}
		{"rifle" lvl_1
		}
		{"rocketlauncher" lvl_1
		}
		{"melee" lvl_1
		}
		
		{"personage" 1
		}		
		
		(include "perks_generic.inc")
		{fortification}
;		{mechanic}
		("barricade_engineer")		
)
(define "perk_scout"
		{"health" "300%"
		}
		{"health_regeneration" "100%"
		}
		{"stamina" "200%"
		}
		{"stamina_regeneration" "200%"
		}
		{"resources" "100%"
		}		
		{"vision" "mp_soldier"
		}
		{"speed" 1.5
		}
		{"stealth"
		}
		{"tank"	1.0
		}
		
		{"pistol" lvl_4
		}
		{"smg" lvl_4
		}
		{"mgun" lvl_4
		}
		{"rifle" lvl_4
		}
		{"rocketlauncher" lvl_4
		}
		{"melee" lvl_4
		}
        {"aimedshot"}		
		
		{"personage" 1
		}		
		
		(include "perks_generic.inc")
		{fortification}
;		{mechanic}
		("barricade_engineer")		
)
(define "perk_shotgun"
		{"health" "350%"
		}
		{"health_regeneration" "100%"
		}
		{"stamina" "200%"
		}
		{"stamina_regeneration" "200%"
		}
		{"resources" "100%"
		}		
		{"vision" "mp_soldier"
		}
		{"speed" 1.2
		}
		{"stealth"
		}
		{"tank"	0.3
		}
		
		{"pistol" lvl_3
		}
		{"smg" lvl_1
		}
		{"mgun" lvl_1
		}
		{"rifle" lvl_4
		}
		{"rocketlauncher" lvl_1
		}
		{"melee" lvl_4
		}
		
		{"personage" 1
		}		
		
		(include "perks_generic.inc")
		{fortification}
;		{mechanic}
		("barricade_engineer")		
)
(define "perk_sniper"
		{"health" "100%"
		}
		{"health_regeneration" "100%"
		}
		{"stamina" "200%"
		}
		{"stamina_regeneration" "200%"
		}
		{"resources" "100%"
		}		
		{"vision" "mp_sniper"
		}
		{"speed" 1.2
		}
		{"stealth"
		}
		{"telescope"
		}		
		{"tank"	0.3
		}
		
		{"pistol" lvl_5
		}
		{"smg" lvl_1
		}
		{"mgun" lvl_1
		}
		{"rifle" lvl_5
		}
		{"rocketlauncher" lvl_1
		}
		{"melee" lvl_1
		}
        {"aimedshot"}		
		
		{"personage" 1
		}		
		
		(include "perks_generic.inc")
		{fortification}
;		{mechanic}
		("barricade_engineer")		
)
(define "perk_squadleader"
		{"health" "200%"
		}
		{"health_regeneration" "100%"
		}
		{"stamina" "200%"
		}
		{"stamina_regeneration" "150%"
		}
		{"resources" "100%"
		}		
		{"vision" "mp_soldier"
		}
		{"speed" 1.0
		}
		{"tank"	0.9
		}
		
		{"pistol" lvl_3
		}
		{"smg" lvl_3
		}
		{"mgun" lvl_3
		}
		{"rifle" lvl_3
		}
		{"rocketlauncher" lvl_3
		}
		{"melee" lvl_3
		}
		
		{"personage" 1
		}		
		
		(include "perks_generic.inc")
		{fortification}
;		{mechanic}
		("barricade_engineer")		
)
(define "perk_sturmovik"
		{"health" "250%"
		}
		{"health_regeneration" "100%"
		}
		{"stamina" "200%"
		}
		{"stamina_regeneration" "200%"
		}
		{"resources" "100%"
		}		
		{"vision" "mp_soldier"
		}
		{"speed" 1.5
		}
;		{"stealth"
;		}
		{"tank"	1.0
		}
		
		{"pistol" lvl_4
		}
		{"smg" lvl_4
		}
		{"mgun" lvl_4
		}
		{"rifle" lvl_4
		}
		{"rocketlauncher" lvl_4
		}
		{"melee" lvl_4
		}
;       {"aimedshot"}		
		
		{"personage" 1
		}		
		
		(include "perks_generic.inc")
		{fortification}
;		{mechanic}
		("barricade_engineer")		
)
(define "perk_tankman"
		{"health" "100%"
		}
		{"health_regeneration" "100%"
		}
		{"stamina" "100%"
		}
		{"stamina_regeneration" "100%"
		}
		{"resources" "100%"
		}		
		{"vision" "mp_soldier"
		}
		{"speed" 1.0
		}
		{"tank"	1.0
		}
		
		{"pistol" lvl_2
		}
		{"smg" lvl_2
		}
		{"mgun" lvl_1
		}
		{"rifle" lvl_1
		}
		{"rocketlauncher" lvl_1
		}
		{"melee" lvl_1
		}		
		
		{"personage" 1
		}		
		
		(include "perks_generic.inc")
		{fortification}
		{mechanic}
		("barricade_engineer")		
)
(define "perk_tankman_veteran"
		{"health" "300%"
		}
		{"health_regeneration" "100%"
		}
		{"stamina" "100%"
		}
		{"stamina_regeneration" "100%"
		}
		{"resources" "100%"
		}		
		{"vision" "mp_soldier"
		}
		{"speed" 1.0
		}
		{"tank"	1.0
		}
		
		{"pistol" lvl_3
		}
		{"smg" lvl_3
		}
		{"mgun" lvl_3
		}
		{"rifle" lvl_3
		}
		{"rocketlauncher" lvl_3
		}
		{"melee" lvl_3
		}		
		
		{"personage" 1
		}		
		
		(include "perks_generic.inc")
		{fortification}
		{mechanic}
		("barricade_engineer")		
)
(define "perk_hero"
		{"health" "350%"
		}
		{"health_regeneration" "150%"
		}
		{"stamina" "250%"
		}
		{"stamina_regeneration" "250%"
		}
		{"resources" "250%"
		}		
		{"vision" "mp_officer"
		}
		{"speed" 1.5
		}
		{"field_glass"
		}
		{"stealth"
		}
		{"telescope"
		}
		{"tank"	2.0
		}
		
		{"pistol" lvl_5
		}
		{"smg" lvl_5
		}
		{"mgun" lvl_5
		}
		{"rifle" lvl_5
		}
		{"rocketlauncher" lvl_5
		}
		{"melee" lvl_5
		}
        {"aimedshot"}		
		
		{"personage" 1
		}		
		
		(include "perks_generic.inc")
		{fortification}
		{mechanic}
		("barricade_engineer")		
)
(define "perk_t1"
		{"health" "200%"
		}
		{"health_regeneration" "100%"
		}
		{"stamina" "100%"
		}
		{"stamina_regeneration" "100%"
		}
		{"resources" "100%"
		}
		{"resources_regeneration" "100%"
		}
		{"vision" "human"
		}
		{"speed" 1.0
		}
		
		{"pistol" lvl_1
		}
		{"smg" lvl_1
		}
		{"mgun" lvl_1
		}
		{"rifle" lvl_1
		}
		{"rocketlauncher" lvl_1
		}
		{"melee" lvl_1
		}
)
(define "perk_t2"
		{"health" "250%"
		}
		{"health_regeneration" "125%"
		}
		{"stamina" "125%"
		}
		{"stamina_regeneration" "125%"
		}
		{"resources" "150%"
		}
		{"resources_regeneration" "125%"
		}
		{"vision" "human"
		}
		{"speed" 1.0
		}
		
		{"pistol" lvl_2
		}
		{"smg" lvl_2
		}
		{"mgun" lvl_2
		}
		{"rifle" lvl_2
		}
		{"rocketlauncher" lvl_2
		}
		{"melee" lvl_2
		}
		
		{"personage" 1
		}
)
(define "perk_t3"
		{"health" "300%"
		}
		{"health_regeneration" "150%"
		}
		{"stamina" "150%"
		}
		{"stamina_regeneration" "150%"
		}
		{"resources" "200%"
		}
		{"resources_regeneration" "150%"
		}
		{"vision" "human"
		}
		{"speed" 1.0
		}
		
		{"pistol" lvl_3
		}
		{"smg" lvl_3
		}
		{"mgun" lvl_3
		}
		{"rifle" lvl_3
		}
		{"rocketlauncher" lvl_3
		}
		{"melee" lvl_3
		}
		
		{"personage" 1
		}
)
(define "perk_t4"
		{"health" "400%"
		}
		{"health_regeneration" "175%"
		}
		{"stamina" "175%"
		}
		{"stamina_regeneration" "175%"
		}
		{"resources" "250%"
		}
		{"resources_regeneration" "175%"
		}
		{"vision" "human"
		}
		{"speed" 1.0
		}
		
		{"pistol" lvl_4
		}
		{"smg" lvl_4
		}
		{"mgun" lvl_4
		}
		{"rifle" lvl_4
		}
		{"rocketlauncher" lvl_4
		}
		{"melee" lvl_4
		}
		
		{"personage" 1
		}
		{"medic" 10.0
		}
)
(define "perk_t5"
		{"health" "500%"
		}
		{"health_regeneration" "200%"
		}
		{"stamina" "200%"
		}
		{"stamina_regeneration" "200%"
		}
		{"resources" "300%"
		}
		{"resources_regeneration" "200%"
		}
		{"vision" "human"
		}
		{"speed" 1.0
		}
		{"stealth"
		}
		
		{"pistol" lvl_5
		}
		{"smg" lvl_5
		}
		{"mgun" lvl_5
		}
		{"rifle" lvl_5
		}
		{"rocketlauncher" lvl_5
		}
		{"melee" lvl_5
		}
		
		{"personage" 1
		}		
		{"medic" 10.0
		}
)
(define "barricade_engineer"
	{barricade
		{"fortifications" "barricade"}
		{"fortifications" "barbwire"}
		{"fortifications" "hedgehog"}
		{"fortifications" "foxhole"}
		{"fortifications" "foxhole_big"}
		{"fortifications" "trench_t"}		
		{"fortifications" "trench_mortar_pit"}		
		{"fortifications" "barricade_sq"}
	}
	{"resources" "250%"
	}
)